# Generated by Django 6.0.2 on 2026-03-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userauth',
            old_name='user_id',
            new_name='user',
        ),
    ]
