# Generated by Django 6.0.2 on 2026-03-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_admin_id_admin_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin',
            new_name='admin_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_id',
        ),
    ]
