# Generated by Django 6.0.2 on 2026-03-13 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_admin_admin_admin_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='id',
        ),
        migrations.AlterField(
            model_name='userauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user'),
        ),
    ]
