# Generated by Django 6.0.2 on 2026-03-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userauth_id_alter_userauth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='email',
        ),
    ]
