# Generated by Django 6.0.2 on 2026-03-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userauth_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_val',
            field=models.TextField(default='fsff3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userauth',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
