# Generated by Django 6.0.2 on 2026-04-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
